name: CI

env:
  DOTNET_VERSION: '8.0'
  ARTIFACT_ROUTE: 'artifacts'
  ARTIFACT_NAME: 'domatrain-artifact'
  AZURE_WEBAPP_NAME: app-dometrain-github-actions-axel
  PROD_AZURE_WEBAPP_NAME: app-dometrain-github-actions-axel-prod

on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --configuration Release --no-build

      - name: Publish artifacts
        run: dotnet publish src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj -o ${{env.ARTIFACT_ROUTE}}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: ${{env.ARTIFACT_ROUTE}}/

  deploy_dev:
    name: Deploy Dev
    needs: build
    uses: ./.github/workflows/steps-deploy.yml
    with:
      env: dev
    secrets: inherit

  deploy_prod:
    name: Deploy Prod
    needs: build
    uses: ./.github/workflows/steps-deploy.yml
    with:
      env: prod
    secrets: inherit