name: Step - Deploy

env:
  AZURE_WEBAPP_NAME: app-dometrain-github-actions-axel
  ARTIFACT_ROUTE: artifacts
  ARTIFACT_NAME: domatrain-artifact

on: 
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      resource_group_name:
        required: true
        type: string
      app_service_name:
        required: true
        type: string        
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:    
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{inputs.env}}

    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: ${{env.ARTIFACT_ROUTE}}/

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{inputs.resource_group_name}}
          slot-name: slot
          package: ${{env.ARTIFACT_ROUTE}}/

      - name: Swap slots
        run: az webapp deploy -g ${{inputs.resource_group_name}} -n ${{inputs.app_service_name}} -slot slot --target-slot production --verbose